# Generated by Django 4.1.4 on 2022-12-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('timings', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.registeruser')),
            ],
        ),
    ]
