# Generated by Django 4.1.4 on 2022-12-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=500)),
                ('user_email', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('user_dob', models.DateField()),
                ('location', models.CharField(max_length=500)),
                ('user_mobile', models.CharField(max_length=500)),
            ],
        ),
    ]
